### ISSUE TITLE
May 09

### ISSUE THREAD

**Issue by codeanit** [codeanit/dsm#10]
What I will did yesterday
- [x] codeanit/til#30 How containers work 2hr
- [x] codeanit/til#20 Docker basics 2hr
- [x] https://github.com/codeanit/til/issues/19 Kubernetes basic concepts 1hr
- [ ] https://github.com/codeanit/til/issues/29 Gatsby further concepts 3hr
- [ ] https://github.com/codeanit/til/issues/60 Host website from home 1hr

What I will do today
- [x] https://github.com/codeanit/til/issues/29 Gatsby further concepts 3hr
- [x] https://github.com/codeanit/til/issues/60 Host website from home 1hr
- [ ] codeanit/til#30 How containers work 2hr
- [ ] codeanit/til#20 Docker basics 2hr
- [ ] https://github.com/codeanit/til/issues/19 Kubernetes basic concepts 1hr

Issues
