### ISSUE TITLE
May 11

### ISSUE THREAD

**Issue by codeanit** [codeanit/dsm#12]
What I will did yesterday
- [x] codeanit/til#30 How containers work 2hr
- [x] codeanit/til#20 Docker basics 2hr
- [x] https://github.com/codeanit/til/issues/19 Kubernetes basic concepts 1hr
- [ ] https://github.com/codeanit/til/issues/29 Gatsby further concepts 3hr
- [ ] https://github.com/codeanit/til/issues/60 Host website from home 1hr

What I will do today
- [x] https://github.com/codeanit/til/issues/19 Kubernetes basic concepts 2hr
- [x] https://github.com/codeanit/til/issues/29 Gatsby further concepts 1hr
- [ ] https://github.com/codeanit/til/issues/60 Host website from home 1hr
- [ ] codeanit/til#30 How containers work 1hr
- [x] codeanit/til#20 Docker basics 1hr
- [x] https://github.com/LearnWithAnit/library/issues/4 Network technologies 1hr | 2hr

Issues

**Comment by codeanit** [comment]
Kubernetes, Docker: 
  Looked at setup up system for Docker and Kubernetes. 
  Reviewed Ansible.

**Comment by codeanit** [comment]
Network Tech: 
  Read chapter 1 and 2.

**Comment by codeanit** [comment]
Gatsby: 
  Review Kentcdodds.com. Went through gatsby-config.js and skimmed the plugins. 
  Also went through the tutorials section in very brief. 
  Wanted to know more about the special files, and it turns out to be a palce holder for the API that Gatsby provides. https://www.gatsbyjs.org/docs/api-reference for further read.
  I was looking for a way to manage the static contents or CMS and https://www.gatsbyjs.org/tutorial/blog-netlify-cms-tutorial looks like the solution.
  https://www.gatsbyjs.org/docs/api-specification to read.
  Need to go through https://www.gatsbyjs.org/tutorial again
