### ISSUE TITLE
May 12

### ISSUE THREAD

**Issue by codeanit** [codeanit/dsm#13]
What I will did yesterday
- [x] https://github.com/codeanit/til/issues/19 Kubernetes basic concepts 2hr
- [x] https://github.com/codeanit/til/issues/29 Gatsby further concepts 1hr
- [ ] https://github.com/codeanit/til/issues/60 Host website from home 1hr
- [ ] codeanit/til#30 How containers work 1hr
- [x] codeanit/til#20 Docker basics 1hr
- [x] https://github.com/LearnWithAnit/library/issues/4 Network technologies 1hr | 2hr

What I will do today
- [x] https://github.com/codeanit/til/issues/60 Host website from home 1hr
- [ ] https://github.com/codeanit/til/issues/29 Gatsby further concepts 2hr
- [ ] https://github.com/LearnWithAnit/library/issues/4 Network technologies 1hr 
- [ ] https://github.com/codeanit/til/issues/66 /proc File system 1hr
- [ ] https://github.com/codeanit/til/issues/65 Linux file system 1hr
- [ ] https://github.com/codeanit/til/issues/61 Nokia router 1hr

Issues

**Comment by codeanit** [comment]
Came to know about Traefik for route and hosting from home.
