### ISSUE TITLE
may 14

### ISSUE THREAD

**Issue by codeanit** [codeanit/dsm#14]
What I will do today
- [x] https://github.com/codeanit/til/issues/29 Gatsby further concepts 2hr
- [x] https://github.com/codeanit/til/issues/60 Host website from home 1hr
- [x] https://github.com/LearnWithAnit/library/issues/4 Network technologies 1hr 
- [ ] https://github.com/codeanit/til/issues/66 /proc File system 1hr
- [ ] https://github.com/codeanit/til/issues/65 Linux file system 1hr
- [ ] https://github.com/codeanit/til/issues/61 Nokia router 1hr

What I  did yesterday
- [x] Reviewed books collection

Issues
- No internet at home

**Comment by codeanit** [comment]
https://linearb.io/blog/why-agile-velocity-is-the-most-dangerous-metric-for-software-development-teams Good read on the Agile.

> TODO
- https://postgresconf.org/conferences/postgres-webinar-series/program/proposals/a-deep-dive-into-postgresql-indexing-6886ab98-e10e-4b58-84a7-dc347aa544db

- https://sloanreview.mit.edu/projects/measuring-culture-in-leading-companies

- You are what you measure - MIT 1998
  https://dspace.mit.edu/handle/1721.1/2703
  https://web.mit.edu/hauser/www/Papers/Hauser-Katz%20Measure%2004-98.pdf
  https://dspace.mit.edu/handle/1721.1/2703  
- https://sloanreview.mit.edu/article/can-you-measure-leadership
- https://mitsloan.mit.edu/ideas-made-to-matter/how-productive-are-you

- https://kalilinuxtutorials.com/gdbfrontend GDBFrontend is an easy, flexible and extensionable gui debugger.

- https://www.cs.toronto.edu/~guerzhoy/tmp/understand-rnn/handout/index.html 

 > con·flate  (kən-flāt′)
  tr.v. con·flat·ed, con·flat·ing, con·flates
  1. To bring together; meld or fuse: "The problems [with the biopic] include ... dates moved around, lovers deleted, many characters conflated into one" (Ty Burr).
  2. To combine (two variant texts, for example) into one whole.
  3. To fail to distinguish between; confuse. See Usage Note below.

**Comment by codeanit** [comment]
Issues when running the kentcdodds code on new pc, installed nvm and stable version of nodejs.

  "gyp ERR! stack Error: not found: make gyp ERR! stack at getNotFoundError"
  Followed https://stackoverflow.com/questions/14772508/npm-failed-to-install-time-with-make-not-found-error, and installed `sudo apt-get install build-essential`
  This solved the error.

  Another issue followed up "Fixing npm/node-gyp Error: not found:"
  Resolved with `sudo apt install build-essential` from https://techoverflow.net/2018/06/04/fixing-npm-node-gyp-error-not-found-make-on-ubuntu

  Another issue followed up - "Error: Cannot find module './build/Release/sharp'"
  Resolved with `apt install libvips` followed by `npm install sharp`

  Another issue  "WorkerError: Processing image.png failed". There seems to be issue while processing large image file in Gatsby. This is listed in common error
  https://www.gatsbyjs.org/docs/troubleshooting-common-errors
  https://github.com/gatsbyjs/gatsby/issues/13442

  Error: ENOSPC: System limit for number of file watchers reached: https://stackoverflow.com/questions/55763428/react-native-error-enospc-system-limit-for-number-of-file-watchers-reached

  There seems to be issue with VSCode as well: https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc

Well in the end removing and and reinstalling made the application functional.
`rm -rf .cache node_modules public package-lock.json`

**Comment by codeanit** [comment]
Network technologies - Completed Ch 3
