### ISSUE TITLE
May 15

### ISSUE THREAD

**Issue by codeanit** [codeanit/dsm#15]
> What I will do today

- [x] https://github.com/codeanit/til/issues/65 Linux file system 1hr
- [x] https://github.com/codeanit/til/issues/66 /proc File system 30mins

- [x] https://github.com/codeanit/til/issues/29 Gatsby review 30mins
- [x] https://github.com/codeanit/codeanit.github.io/issues/1 Site design layout 1hr

- [x] https://github.com/codeanit/til/issues/92 Security for beginners 30mins

- [x] https://github.com/codeanit/til/issues/93 TCP/IP Overview 1hr

- [x] https://github.com/LearnWithAnit/library/issues/4 Network technologies 1hr
  - [x] Learning Preparation Tasks
  - [ ] Chapter 4
 
 
- [x] https://github.com/codeanit/til/issues/60 Host website from home 1hr

- [x] https://github.com/codeanit/til/issues/61 CLI Nokia router 1hr

Issues
