### ISSUE TITLE
May 16

### ISSUE THREAD

**Issue by codeanit** [codeanit/dsm#16]
> What I will do today

- [x] https://github.com/codeanit/til/issues/20 Docker 2hr

- [ ] https://github.com/codeanit/til/issues/29 Gatsby review 30mins
- [ ] https://github.com/codeanit/codeanit.github.io/issues/1 Site design layout 1hr

- [ ] https://github.com/codeanit/til/issues/92 Security for beginners 30mins

- [ ] Review and wrap up 
  - [ ] https://github.com/codeanit/til/issues/65 Linux file system 30hr
  - [ ] https://github.com/codeanit/til/issues/66 /proc File system 30mins

- [ ] https://github.com/codeanit/til/issues/93 TCP/IP Ch1 1hr

- [x] https://github.com/LearnWithAnit/library/issues/4 Network technologies 1hr
  - [x] Chapters 1-3 review
  - [ ] Chapter 4

- [ ] https://github.com/codeanit/til/issues/61 Review and close issue 15mins
  CLI Nokia router

- [ ] https://github.com/codeanit/til/issues/18 Elastic stack 1hr 

Issues

**Comment by codeanit** [comment]
Network technologies Reviewed till chapter 2.
