### ISSUE TITLE
May 21

### ISSUE THREAD

**Issue by codeanit** [codeanit/dsm#21]
What I will do today

- [x] https://github.com/codeanit/til/issues/111 Gatsby theme 4hr

- [x] https://github.com/codeanit/til/issues/20 Docker basics 1hr

- [ ] https://github.com/codeanit/til/issues/19 K8s 1hr

- [ ] https://github.com/codeanit/til/issues/92 30mins

- [x] https://github.com/LearnWithAnit/library/issues/11 | https://github.com/codeanit/til/issues/93 Network admin 1hr Ch1/2/3

- [ ]  https://github.com/LearnWithAnit/library/issues/4 Open source network 2hr
  Review ch 1/2/3. Go through Ch4 
 
- [x] [The art of war](https://github.com/LearnWithAnit/library/issues/16) Audio

**Comment by codeanit** [comment]
> Note: 
  Do not make issues from Library [Issues](https://github.com/LearnWithAnit/library/issues)  in TIL.
  Make issues based on the title of the chapters. TIL should be more specific.
