### ISSUE TITLE
May 22

### ISSUE THREAD

**Issue by codeanit** [codeanit/dsm#22]
What I will do today

- [ ] https://github.com/codeanit/til/issues/19 K8s 1hr

- [x] https://github.com/codeanit/til/issues/92 30mins

- [ ] https://github.com/LearnWithAnit/library/issues/11 | https://github.com/codeanit/til/issues/93 Ch1 Network admin 1hr 

- [ ]  https://github.com/LearnWithAnit/library/issues/4 Open source network 2hr
  Review ch 1/2/3. Go through Ch4 
 
- [x] https://github.com/codeanit/til/issues/111 Gatsby theme 1hr
- [ ] https://github.com/codeanit/til/issues/116 Ubuntu internet issue 1hr 
- [ ] [The art of war](https://github.com/LearnWithAnit/library/issues/16) Audio  

- [ ] Make issues for the books in the [library](https://github.com/learnWithAnit/library/issues)

- [ ] https://github.com/codeanit/til/issues/118 Kali Linux 1hr
