### ISSUE TITLE
May 23

### ISSUE THREAD

**Issue by codeanit** [codeanit/dsm#23]
What I will do today

- [x] https://github.com/codeanit/til/issues/99 Nokia router security 3hr
- [ ] https://github.com/codeanit/til/issues/19 K8s 1hr
- [x] https://github.com/codeanit/til/issues/118 Kali Linux 1hr
- [x] https://github.com/codeanit/til/issues/120 Metasploit 1hr
- [x] https://github.com/codeanit/til/issues/119 Docker security 1hr
- [x] https://github.com/codeanit/til/issues/123 GhostDNS
