### ISSUE TITLE
May 24

### ISSUE THREAD

**Issue by codeanit** [codeanit/dsm#24]
What I will do today

- [ ] https://github.com/codeanit/til/issues/19 K8s 1hr

- [ ] https://github.com/codeanit/til/issues/118 Kali Linux 1hr
- [ ] https://github.com/codeanit/til/issues/120 Metasploit 1hr

- [ ] https://github.com/codeanit/til/issues/119 Docker security 15mins
- [ ] https://github.com/codeanit/til/issues/123 GhostDNS 30mins

- [ ] https://github.com/codeanit/til/issues/117 TS with React 1hr
- [ ] https://github.com/LearnWithAnit/library/issues/4 OpenSource N/W 1hr
