### ISSUE TITLE
May 26

### ISSUE THREAD

**Issue by codeanit** [codeanit/dsm#26]
# What I will do today

- [ ] https://github.com/codeanit/til/issues/19 K8s 1hr

> Security
- [x] https://github.com/codeanit/til/issues/100 Pentest
- [ ] https://github.com/LearnWithAnit/cybersecurity-tryhackme/issues/1 Pentest Youtube example 
- [ ] https://github.com/codeanit/til/issues/129 Cyber security audit
- [ ] https://github.com/codeanit/til/issues/120 Metasploit 30mins
- [x] https://github.com/codeanit/til/issues/135 Aircrack-ng 15mins
- [ ] https://github.com/codeanit/til/issues/119 Docker security 15mins
- [ ] https://github.com/codeanit/til/issues/123 GhostDNS 30mins

> Website
  - [x] https://github.com/codeanit/til/issues/117 TS with React 1hr
  - [ ] https://github.com/codeanit-website/website/issues/2 codeanit.com Gatsby impl

> Network
- [ ] https://github.com/LearnWithAnit/library/issues/4 OpenSource N/W 1hr
  Review Chapter 1-3
  Chapter 4

- [ ]  Chapter 1: Overview of TCP/IP 1hr
  Chapter 1: Review
  Chapter 2: Delivering the Data
