### ISSUE TITLE
May 1

### ISSUE THREAD

**Issue by codeanit** [codeanit/dsm#4]
What I did yesterday
- [ ] https://github.com/codeanit/codeanit.github.io/issues/3 How to make Gatsby site live
- [ ] codeanit/til#31 StatsD
- [ ] codeanit/til#18 Elastic Stack

What I will do today
- [ ] https://github.com/codeanit/codeanit.github.io/issues/3 Plugins/Templates, Live the blog site.
- [ ] codeanit/til#31 StatsD
- [ ] codeanit/til#18 Elastic Stack
- [ ] codeanit/opensource#11 Coding Coach
- [ ] codeanit/til#19 K8s basics
- [ ] codeanit/til#20 Docker basics
- [ ] codeanit/til#30 How containers work

Issues
