### ISSUE TITLE
May 02

### ISSUE THREAD

**Issue by codeanit** [codeanit/dsm#5]
What I did yesterday
- [ ] https://github.com/codeanit/codeanit.github.io/issues/3 How to make Gatsby site live

What I will do today
- [ ] Hackathon 
- [ ] https://github.com/codeanit/codeanit.github.io/issues/3 Plugins/Templates, Live the blog site.
- [ ] codeanit/til#31 StatsD
- [ ] codeanit/til#18 Elastic Stack
- [ ] codeanit/opensource#11 Coding Coach
- [ ] codeanit/til#19 K8s basics
- [ ] codeanit/til#20 Docker basics
- [ ] codeanit/til#30 How containers work

Issues

**Comment by codeanit** [comment]
Hackathon participation.
