### ISSUE TITLE
May 04

### ISSUE THREAD

**Issue by codeanit** [codeanit/dsm#7]
What I did yesterday
- [x] Hackathon

What I will do today
- [ ] https://github.com/codeanit/til/issues/46: Install Linux on Sony Aqua
- [ ] codeanit/til#30 How containers work
- [ ] codeanit/til#20 Docker basics

Issues
