### ISSUE TITLE
May 05

### ISSUE THREAD

**Issue by codeanit** [codeanit/dsm#8]
What I will did yesterday

What I will do today
- [x] https://github.com/codeanit/til/issues/46: Install Linux on Sony Aqua
- [ ] codeanit/til#30 How containers work
- [ ] codeanit/til#20 Docker basics
- [ ] https://github.com/codeanit/til/issues/29 Gatsby further concepts

Issue
