### ISSUE TITLE
May 07

### ISSUE THREAD

**Issue by codeanit** [codeanit/dsm#9]
What I will did yesterday
- [x] https://github.com/codeanit/til/issues/60 Host website from home 1hr
- [x] https://github.com/codeanit/til/issues/61 Nokia router CLI access 

What I will do today
- [x] codeanit/til#30 How containers work 2hr
- [x] codeanit/til#20 Docker basics 2hr
- [x] https://github.com/codeanit/til/issues/19 Kubernetes basic concepts 1hr
- [ ] https://github.com/codeanit/til/issues/29 Gatsby further concepts 3hr
- [ ] https://github.com/codeanit/til/issues/60 Host website from home 1hr

Issue
